export const demoData = [
  { country: "Afghanistan", code: "AF", dial_code: "+93" },
  { country: "Albania", code: "AL", dial_code: "+355" },
  { country: "Algeria", code: "DZ", dial_code: "+213" },
  { country: "Andorra", code: "AD", dial_code: "+376" },
  { country: "Angola", code: "AO", dial_code: "+244" },
  { country: "Antigua and Barbuda", code: "AG", dial_code: "+1-268" },
  { country: "Argentina", code: "AR", dial_code: "+54" },
  { country: "Armenia", code: "AM", dial_code: "+374" },
  { country: "Australia", code: "AU", dial_code: "+61" },
  { country: "Austria", code: "AT", dial_code: "+43" },
  { country: "Azerbaijan", code: "AZ", dial_code: "+994" },
  { country: "Bahamas", code: "BS", dial_code: "+1-242" },
  { country: "Bahrain", code: "BH", dial_code: "+973" },
  { country: "Bangladesh", code: "BD", dial_code: "+880" },
  { country: "Barbados", code: "BB", dial_code: "+1-246" },
  { country: "Belarus", code: "BY", dial_code: "+375" },
  { country: "Belgium", code: "BE", dial_code: "+32" },
  { country: "Belize", code: "BZ", dial_code: "+501" },
  { country: "Benin", code: "BJ", dial_code: "+229" },
  { country: "Bhutan", code: "BT", dial_code: "+975" },
  { country: "Bolivia", code: "BO", dial_code: "+591" },
  { country: "Bosnia and Herzegovina", code: "BA", dial_code: "+387" },
  { country: "Botswana", code: "BW", dial_code: "+267" },
  { country: "Brazil", code: "BR", dial_code: "+55" },
  { country: "Brunei", code: "BN", dial_code: "+673" },
  { country: "Bulgaria", code: "BG", dial_code: "+359" },
  { country: "Burkina Faso", code: "BF", dial_code: "+226" },
  { country: "Burundi", code: "BI", dial_code: "+257" },
  { country: "Cabo Verde", code: "CV", dial_code: "+238" },
  { country: "Cambodia", code: "KH", dial_code: "+855" },
  { country: "Cameroon", code: "CM", dial_code: "+237" },
  { country: "Canada", code: "CA", dial_code: "+1" },
  { country: "Central African Republic", code: "CF", dial_code: "+236" },
  { country: "Chad", code: "TD", dial_code: "+235" },
  { country: "Chile", code: "CL", dial_code: "+56" },
  { country: "China", code: "CN", dial_code: "+86" },
  { country: "Colombia", code: "CO", dial_code: "+57" },
  { country: "Comoros", code: "KM", dial_code: "+269" },
  { country: "Congo (Congo-Brazzaville)", code: "CG", dial_code: "+242" },
  { country: "Congo (Democratic Republic)", code: "CD", dial_code: "+243" },
  { country: "Costa Rica", code: "CR", dial_code: "+506" },
  { country: "Croatia", code: "HR", dial_code: "+385" },
  { country: "Cuba", code: "CU", dial_code: "+53" },
  { country: "Cyprus", code: "CY", dial_code: "+357" },
  { country: "Czechia (Czech Republic)", code: "CZ", dial_code: "+420" },
  { country: "Denmark", code: "DK", dial_code: "+45" },
  { country: "Djibouti", code: "DJ", dial_code: "+253" },
  { country: "Dominica", code: "DM", dial_code: "+1-767" },
  { country: "Dominican Republic", code: "DO", dial_code: "+1-809" },
  { country: "Ecuador", code: "EC", dial_code: "+593" },
  { country: "Egypt", code: "EG", dial_code: "+20" },
  { country: "El Salvador", code: "SV", dial_code: "+503" },
  { country: "Equatorial Guinea", code: "GQ", dial_code: "+240" },
  { country: "Eritrea", code: "ER", dial_code: "+291" },
  { country: "Estonia", code: "EE", dial_code: "+372" },
  { country: "Eswatini (fmr. 'Swaziland')", code: "SZ", dial_code: "+268" },
  { country: "Ethiopia", code: "ET", dial_code: "+251" },
  { country: "Fiji", code: "FJ", dial_code: "+679" },
  { country: "Finland", code: "FI", dial_code: "+358" },
  { country: "France", code: "FR", dial_code: "+33" },
  { country: "Gabon", code: "GA", dial_code: "+241" },
  { country: "Gambia", code: "GM", dial_code: "+220" },
  { country: "Georgia", code: "GE", dial_code: "+995" },
  { country: "Germany", code: "DE", dial_code: "+49" },
  { country: "Ghana", code: "GH", dial_code: "+233" },
  { country: "Greece", code: "GR", dial_code: "+30" },
  { country: "Grenada", code: "GD", dial_code: "+1-473" },
  { country: "Guatemala", code: "GT", dial_code: "+502" },
  { country: "Guinea", code: "GN", dial_code: "+224" },
  { country: "Guinea-Bissau", code: "GW", dial_code: "+245" },
  { country: "Guyana", code: "GY", dial_code: "+592" },
  { country: "Haiti", code: "HT", dial_code: "+509" },
  { country: "Honduras", code: "HN", dial_code: "+504" },
  { country: "Hungary", code: "HU", dial_code: "+36" },
  { country: "Iceland", code: "IS", dial_code: "+354" },
  { country: "India", code: "IN", dial_code: "+91" },
  { country: "Indonesia", code: "ID", dial_code: "+62" },
  { country: "Iran", code: "IR", dial_code: "+98" },
  { country: "Iraq", code: "IQ", dial_code: "+964" },
  { country: "Ireland", code: "IE", dial_code: "+353" },
  { country: "Israel", code: "IL", dial_code: "+972" },
  { country: "Italy", code: "IT", dial_code: "+39" },
  { country: "Jamaica", code: "JM", dial_code: "+1-876" },
  { country: "Japan", code: "JP", dial_code: "+81" },
  { country: "Jordan", code: "JO", dial_code: "+962" },
  { country: "Kazakhstan", code: "KZ", dial_code: "+7" },
  { country: "Kenya", code: "KE", dial_code: "+254" },
  { country: "Kiribati", code: "KI", dial_code: "+686" },
  { country: "Kuwait", code: "KW", dial_code: "+965" },
  { country: "Kyrgyzstan", code: "KG", dial_code: "+996" },
  { country: "Laos", code: "LA", dial_code: "+856" },
  { country: "Latvia", code: "LV", dial_code: "+371" },
  { country: "Lebanon", code: "LB", dial_code: "+961" },
  { country: "Lesotho", code: "LS", dial_code: "+266" },
  { country: "Liberia", code: "LR", dial_code: "+231" },
  { country: "Libya", code: "LY", dial_code: "+218" },
  { country: "Liechtenstein", code: "LI", dial_code: "+423" },
  { country: "Lithuania", code: "LT", dial_code: "+370" },
  { country: "Luxembourg", code: "LU", dial_code: "+352" },
  { country: "Madagascar", code: "MG", dial_code: "+261" },
  { country: "Malawi", code: "MW", dial_code: "+265" },
  { country: "Malaysia", code: "MY", dial_code: "+60" },
  { country: "Maldives", code: "MV", dial_code: "+960" },
  { country: "Mali", code: "ML", dial_code: "+223" },
  { country: "Malta", code: "MT", dial_code: "+356" },
  { country: "Marshall Islands", code: "MH", dial_code: "+692" },
  { country: "Mauritania", code: "MR", dial_code: "+222" },
  { country: "Mauritius", code: "MU", dial_code: "+230" },
  { country: "Mexico", code: "MX", dial_code: "+52" },
  { country: "Micronesia", code: "FM", dial_code: "+691" },
  { country: "Moldova", code: "MD", dial_code: "+373" },
  { country: "Monaco", code: "MC", dial_code: "+377" },
  { country: "Mongolia", code: "MN", dial_code: "+976" },
  { country: "Montenegro", code: "ME", dial_code: "+382" },
  { country: "Morocco", code: "MA", dial_code: "+212" },
  { country: "Mozambique", code: "MZ", dial_code: "+258" },
  { country: "Myanmar (formerly Burma)", code: "MM", dial_code: "+95" },
  { country: "Namibia", code: "NA", dial_code: "+264" },
  { country: "Nauru", code: "NR", dial_code: "+674" },
  { country: "Nepal", code: "NP", dial_code: "+977" },
  { country: "Netherlands", code: "NL", dial_code: "+31" },
  { country: "New Zealand", code: "NZ", dial_code: "+64" },
  { country: "Nicaragua", code: "NI", dial_code: "+505" },
  { country: "Niger", code: "NE", dial_code: "+227" },
  { country: "Nigeria", code: "NG", dial_code: "+234" },
  { country: "North Korea", code: "KP", dial_code: "+850" },
  { country: "North Macedonia", code: "MK", dial_code: "+389" },
  { country: "Norway", code: "NO", dial_code: "+47" },
  { country: "Oman", code: "OM", dial_code: "+968" },
  { country: "Pakistan", code: "PK", dial_code: "+92" },
  { country: "Palau", code: "PW", dial_code: "+680" },
  { country: "Palestine", code: "PS", dial_code: "+970" },
  { country: "Panama", code: "PA", dial_code: "+507" },
  { country: "Papua New Guinea", code: "PG", dial_code: "+675" },
  { country: "Paraguay", code: "PY", dial_code: "+595" },
  { country: "Peru", code: "PE", dial_code: "+51" },
  { country: "Philippines", code: "PH", dial_code: "+63" },
  { country: "Poland", code: "PL", dial_code: "+48" },
  { country: "Portugal", code: "PT", dial_code: "+351" },
  { country: "Qatar", code: "QA", dial_code: "+974" },
  { country: "Romania", code: "RO", dial_code: "+40" },
  { country: "Russia", code: "RU", dial_code: "+7" },
  { country: "Rwanda", code: "RW", dial_code: "+250" },
  { country: "Saint Kitts and Nevis", code: "KN", dial_code: "+1-869" },
  { country: "Saint Lucia", code: "LC", dial_code: "+1-758" },
  {
    country: "Saint Vincent and the Grenadines",
    code: "VC",
    dial_code: "+1-784",
  },
  { country: "Samoa", code: "WS", dial_code: "+685" },
  { country: "San Marino", code: "SM", dial_code: "+378" },
  { country: "Sao Tome and Principe", code: "ST", dial_code: "+239" },
  { country: "Saudi Arabia", code: "SA", dial_code: "+966" },
  { country: "Senegal", code: "SN", dial_code: "+221" },
  { country: "Serbia", code: "RS", dial_code: "+381" },
  { country: "Seychelles", code: "SC", dial_code: "+248" },
  { country: "Sierra Leone", code: "SL", dial_code: "+232" },
  { country: "Singapore", code: "SG", dial_code: "+65" },
  { country: "Slovakia", code: "SK", dial_code: "+421" },
  { country: "Slovenia", code: "SI", dial_code: "+386" },
  { country: "Solomon Islands", code: "SB", dial_code: "+677" },
  { country: "Somalia", code: "SO", dial_code: "+252" },
  { country: "South Africa", code: "ZA", dial_code: "+27" },
  { country: "South Korea", code: "KR", dial_code: "+82" },
  { country: "South Sudan", code: "SS", dial_code: "+211" },
  { country: "Spain", code: "ES", dial_code: "+34" },
  { country: "Sri Lanka", code: "LK", dial_code: "+94" },
  { country: "Sudan", code: "SD", dial_code: "+249" },
  { country: "Suriname", code: "SR", dial_code: "+597" },
  { country: "Sweden", code: "SE", dial_code: "+46" },
  { country: "Switzerland", code: "CH", dial_code: "+41" },
  { country: "Syria", code: "SY", dial_code: "+963" },
  { country: "Taiwan", code: "TW", dial_code: "+886" },
  { country: "Tajikistan", code: "TJ", dial_code: "+992" },
  { country: "Tanzania", code: "TZ", dial_code: "+255" },
  { country: "Thailand", code: "TH", dial_code: "+66" },
  { country: "Timor-Leste", code: "TL", dial_code: "+670" },
  { country: "Togo", code: "TG", dial_code: "+228" },
  { country: "Tonga", code: "TO", dial_code: "+676" },
  { country: "Trinidad and Tobago", code: "TT", dial_code: "+1-868" },
  { country: "Tunisia", code: "TN", dial_code: "+216" },
  { country: "Turkey", code: "TR", dial_code: "+90" },
  { country: "Turkmenistan", code: "TM", dial_code: "+993" },
  { country: "Tuvalu", code: "TV", dial_code: "+688" },
  { country: "Uganda", code: "UG", dial_code: "+256" },
  { country: "Ukraine", code: "UA", dial_code: "+380" },
  { country: "United Arab Emirates", code: "AE", dial_code: "+971" },
  { country: "United Kingdom", code: "GB", dial_code: "+44" },
  { country: "United States", code: "US", dial_code: "+1" },
  { country: "Uruguay", code: "UY", dial_code: "+598" },
  { country: "Uzbekistan", code: "UZ", dial_code: "+998" },
  { country: "Vanuatu", code: "VU", dial_code: "+678" },
  { country: "Vatican City (Holy See)", code: "VA", dial_code: "+379" },
  { country: "Venezuela", code: "VE", dial_code: "+58" },
  { country: "Vietnam", code: "VN", dial_code: "+84" },
  { country: "Yemen", code: "YE", dial_code: "+967" },
  { country: "Zambia", code: "ZM", dial_code: "+260" },
  { country: "Zimbabwe", code: "ZW", dial_code: "+263" },
];
